# Generated by Django 2.2.1 on 2019-05-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_availability', models.BooleanField(default=True)),
                ('doctor_specialisation', models.CharField(max_length=200)),
                ('doctor_shift_slot1_from', models.TimeField()),
                ('doctor_shift_slot1_to', models.TimeField()),
                ('doctor_shift_slot2_from', models.TimeField()),
                ('doctor_shift_slot2_to', models.TimeField()),
                ('doctor_sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PatientSteggedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_state', models.CharField(choices=[('N', 'normal'), ('U', 'need urgent attention'), ('E', 'emergency')], default='N', max_length=25)),
                ('patient_new', models.BooleanField(default=True)),
                ('patient_age', models.IntegerField(null=True)),
                ('patient_DOB', models.DateField(null=True)),
                ('reason_for_consultation', models.CharField(max_length=300, null=True)),
                ('appointment_date_time', models.DateTimeField(null=True)),
                ('appointment_form_submission_date_time', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontdesk.DoctorDetails')),
            ],
        ),
    ]
