# Generated by Django 2.2.1 on 2019-05-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_availability', models.BooleanField(default=True)),
                ('doctor_specialisation', models.CharField(max_length=200)),
                ('doctor_shift_slot1', models.IntegerField(default=0)),
                ('doctor_shift_slot2', models.IntegerField(default=0)),
                ('doctor_sex', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=14)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('patient_hash', models.CharField(max_length=64)),
                ('appointment_doctor', models.CharField(max_length=50)),
                ('doctor_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontdesk.DoctorDetails')),
            ],
        ),
    ]
