# Generated by Django 2.2.1 on 2019-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='appointment_reason',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
