# Generated by Django 2.2.1 on 2019-05-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsteggeddetails',
            name='patient',
        ),
    ]
