# Generated by Django 2.2.1 on 2019-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0003_auto_20190526_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsteggeddetails',
            name='patient_steg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
